=== Nasajon/nsbuild/nsjBuild/xml/nsjBuildProject.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.nasajon.com.br/nsjbuild"
			elementFormDefault="qualified"
			attributeFormDefault="unqualified"
			xmlns:nsjb="http://www.nasajon.com.br/nsjbuild">

	<xs:element name="projeto">
        <xs:complexType>
			<xs:sequence>
				
				<xs:element name="nome" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Nome do projeto (identificador que precisa ser único; sugere-se utilizar o nome do arquivo ".dproj").
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Nome do programdor responsável pela criação do pacote (sugere-se utilizar a identidade Nasajon).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dataCriacao" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Data e hora da criação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resumo" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Comentário para documentação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="path" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Caminho relativo do projeto, a partir do diretório do repositório "erp" (caminho do arquivo "dproj" do projeto atual).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dependencias" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Lista de projetos dos quais o projeto atual depende.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dependencia" type="xs:string" minOccurs="1" maxOccurs="1000">
								<xs:annotation>
									<xs:documentation>
										Nome do projeto do qual o projeto atual depende.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ignore" type="xs:boolean" minOccurs="0" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Se for true, o projeto será ignorado pelo nsbuild (não entrará no grafo de compilação).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
    </xs:element>
</xs:schema>

=== Nasajon/nsbuild/nsjBuild/xmls/NSJADMIN.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>nsjadmin</nome>
    <autor>[Identidade Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\projects\admin\nsjAdmin.dproj</path>
    <dependencias>
        <dependencia>limitedecredito</dependencia>
        <dependencia>exclusaoempresas</dependencia>
        <dependencia>ciclofaturamento</dependencia>
        <dependencia>nsimportador</dependencia>
        <dependencia>nsreport</dependencia>
        <dependencia>atualizador_classificacaofinanceira</dependencia>
        <dependencia>nslicenciamento</dependencia>
        <dependencia>objetosservicosbase</dependencia>
        <dependencia>elementosdecontrolebase</dependencia>
        <dependencia>contafinanceira</dependencia>
        <dependencia>nsintegradorged</dependencia>
        <dependencia>nsjagente</dependencia>
        <dependencia>centrodecustofinanceiro</dependencia>
        <dependencia>rateiopadrao</dependencia>
        <dependencia>nseditorconsultas</dependencia>
        <dependencia>perfilusuariosistema</dependencia>
        <dependencia>configuracao</dependencia>
        <dependencia>nsdicionariodedados</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>objetosservicos</dependencia>
        <dependencia>integracaofinancaspersona</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>classificacaofinanceira</dependencia>
        <dependencia>banco</dependencia>
        <dependencia>bloqueios</dependencia>
        <dependencia>documentosservicedocument</dependencia>
        <dependencia>projetofinanceiro</dependencia>
        <dependencia>nsproxy</dependencia>
        <dependencia>nsmenufavoritos</dependencia>
        <dependencia>nsjapi</dependencia>
        <dependencia>nstraducao</dependencia>
        <dependencia>nsbackup</dependencia>
        <dependencia>nsprotecao</dependencia>
        <dependencia>workflowcommonfeature</dependencia>
        <dependencia>nsbroker</dependencia>
        <dependencia>usuario</dependencia>
        <dependencia>v2</dependencia>
        <dependencia>elementosdecontrole</dependencia>
        <dependencia>nslog</dependencia>
        <dependencia>entidadesempresariais</dependencia>
        <dependencia>nstestframework</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/clientes.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>clientes</nome>
    <path>source\desktop_new\commonfeature\clientes\package\clientes.dproj</path>
    <dependencias>
        <dependencia>rpsbase</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>rps</dependencia>
        <dependencia>proposta</dependencia>
        <dependencia>financeiro</dependencia>
        <dependencia>dashboardclientes</dependencia>
        <dependencia>propostabase</dependencia>
        <dependencia>resources</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/nsjagente.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>nsjagente</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\projects\agente\nsjAgente.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsws</dependencia>
        <dependencia>persona</dependencia>
        <dependencia>rps</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>nsjpersona</dependencia>
        <dependencia>nsjusuarios</dependencia>
        <dependencia>v2</dependencia>
        <dependencia>nsproxy</dependencia>
        <dependencia>nsjapi</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls_bkp/NCM.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>NCM</nome>
    <path>source\desktop_new\commonfeature\ncm\package\ncm.dproj</path>
    <dependencias>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>PERFILIMPORTACAO</dependencia>
        <dependencia>NSORM</dependencia>
        <dependencia>USUARIO</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/PROPOSTAOPERACAO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>propostaoperacao</nome>
    <path>source\desktop_new\commonfeature\proposta\operacao\package\propostaoperacao.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>objetosservicos</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>financeiro</dependencia>
        <dependencia>catalogodeofertas</dependencia>
        <dependencia>operacaoordemservico</dependencia>
        <dependencia>objetosservicosbase</dependencia>
        <dependencia>modelosnaturezas</dependencia>
        <dependencia>naturezascontratos</dependencia>
        <dependencia>nstraducao</dependencia>
        <dependencia>documentositens</dependencia>
        <dependencia>documenttemplate</dependencia>
        <dependencia>operacoes</dependencia>
        <dependencia>formapagamento</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/FOLLOWUP.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>followup</nome>
    <path>source\desktop_new\commonfeature\followup\package\followup.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>nsjusuarios</dependencia>
        <dependencia>historicospadrao</dependencia>
        <dependencia>tiposfollowups</dependencia>
        <dependencia>promocoesleads</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/objetosservicosbase.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>objetosservicosbase</nome>
    <path>source\desktop_new\commonfeature\objetosservicosbase\package\objetosservicosbase.dproj</path>
    <dependencias>
        <dependencia>nstraducao</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>elementosdecontrolebase</dependencia>
        <dependencia>configuracao</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/NSJCONVERSOR.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>nsjconversor</nome>
    <path>source\desktop_new\projects\conversor\nsjConversor.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsprotecao</dependencia>
        <dependencia>nsjpersona</dependencia>
        <dependencia>nsxeutil</dependencia>
        <dependencia>usuario</dependencia>
        <dependencia>nsjcontabil</dependencia>
        <dependencia>nslog</dependencia>
        <dependencia>nsjapi</dependencia>
    </dependencias>
</projeto>
