=== Nasajon/nsbuild/nsjBuild/xml/nsjBuildProject.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.nasajon.com.br/nsjbuild"
			elementFormDefault="qualified"
			attributeFormDefault="unqualified"
			xmlns:nsjb="http://www.nasajon.com.br/nsjbuild">

	<xs:element name="projeto">
        <xs:complexType>
			<xs:sequence>
				
				<xs:element name="nome" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Nome do projeto (identificador que precisa ser único; sugere-se utilizar o nome do arquivo ".dproj").
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Nome do programdor responsável pela criação do pacote (sugere-se utilizar a identidade Nasajon).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dataCriacao" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Data e hora da criação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resumo" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Comentário para documentação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="path" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Caminho relativo do projeto, a partir do diretório do repositório "erp" (caminho do arquivo "dproj" do projeto atual).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dependencias" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Lista de projetos dos quais o projeto atual depende.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dependencia" type="xs:string" minOccurs="1" maxOccurs="1000">
								<xs:annotation>
									<xs:documentation>
										Nome do projeto do qual o projeto atual depende.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ignore" type="xs:boolean" minOccurs="0" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Se for true, o projeto será ignorado pelo nsbuild (não entrará no grafo de compilação).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
    </xs:element>
</xs:schema>

=== Nasajon/nsbuild/nsjBuild/xmls/PRODUTO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>produto</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\commonfeature\produto\package\produto.dproj</path>
    <dependencias>
        <dependencia>ipienquadramento</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>localdeestoqueendereco</dependencia>
        <dependencia>itemestabelecimento</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>perfiltributario</dependencia>
        <dependencia>numeroserie</dependencia>
        <dependencia>nsintegradorged</dependencia>
        <dependencia>figuratributaria</dependencia>
        <dependencia>grade</dependencia>
        <dependencia>ncm</dependencia>
        <dependencia>usuario</dependencia>
        <dependencia>scrittamateriais</dependencia>
        <dependencia>resources</dependencia>
        <dependencia>etiqueta_base</dependencia>
        <dependencia>categoriadeproduto</dependencia>
        <dependencia>configuracao</dependencia>
        <dependencia>operacoes</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls_bkp/CONTRATO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>CONTRATO</nome>
    <path>source\desktop_new\commonfeature\contrato\package\contrato.dproj</path>
    <dependencias>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>ITENSFATURAMENTOBASE</dependencia>
        <dependencia>NSORM</dependencia>
        <dependencia>OBJETOSSERVICOSBASE</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls_bkp/ATENDIMENTO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>ATENDIMENTO</nome>
    <path>source\desktop_new\commonfeature\atendimentos\package\atendimento.dproj</path>
    <dependencias>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>NSJREPORTEDITOR</dependencia>
        <dependencia>OBJETOSSERVICOS</dependencia>
        <dependencia>SERVICOSTECNICOS</dependencia>
        <dependencia>NSORM</dependencia>
        <dependencia>NSREPORT</dependencia>
        <dependencia>OBJETOSSERVICOSBASE</dependencia>
        <dependencia>OPERACAOORDEMSERVICO</dependencia>
        <dependencia>TIPOSFOLLOWUPS</dependencia>
        <dependencia>RELATORIOS</dependencia>
        <dependencia>FOLLOWUP</dependencia>
        <dependencia>NSTRADUCAO</dependencia>
        <dependencia>TIPOSORDENSSERVICOS</dependencia>
        <dependencia>PRODUTO</dependencia>
        <dependencia>NSJUSUARIOS</dependencia>
        <dependencia>TIPOSMANUTENCOES</dependencia>
        <dependencia>PRIORIDADESATENDIMENTOS</dependencia>
        <dependencia>REQUISICAOALMOXARIFADO</dependencia>
        <dependencia>USUARIO</dependencia>
        <dependencia>RESOURCES</dependencia>
        <dependencia>CONFIGURACAO</dependencia>
        <dependencia>OPERACOES</dependencia>
        <dependencia>ENTIDADESEMPRESARIAIS</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/CONTASPADROES.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>contaspadroes</nome>
    <path>source\desktop_new\commonfeature\contaspadroes\package\contaspadroes.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>contafinanceira</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/BANCO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>banco</nome>
    <path>source\desktop_new\commonfeature\banco\package\banco.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>nsjapi</dependencia>
    </dependencias>
    <ultimaCompilacao>2016-08-20T09:39:07.431-03:00</ultimaCompilacao>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/ncm.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>ncm</nome>
    <path>source\desktop_new\commonfeature\ncm\package\ncm.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>perfilimportacao</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>usuario</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/nsjestoque.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>nsjestoque</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\projects\estoque\projeto\nsjEstoque.dproj</path>
    <dependencias>
        <dependencia>limitedecredito</dependencia>
        <dependencia>arquivolayout</dependencia>
        <dependencia>nsjreporteditor</dependencia>
        <dependencia>consultadocengine</dependencia>
        <dependencia>nsreport</dependencia>
        <dependencia>objetosservicosbase</dependencia>
        <dependencia>nslicenciamento</dependencia>
        <dependencia>relatorios</dependencia>
        <dependencia>centrodecustofinanceiro</dependencia>
        <dependencia>geradordedocumento</dependencia>
        <dependencia>rateiopadrao</dependencia>
        <dependencia>figuratributaria</dependencia>
        <dependencia>nsjusuarios</dependencia>
        <dependencia>inventario</dependencia>
        <dependencia>item</dependencia>
        <dependencia>perfilimportacao</dependencia>
        <dependencia>workflow</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>cfop</dependencia>
        <dependencia>nsjapi</dependencia>
        <dependencia>nstraducao</dependencia>
        <dependencia>nsprotecao</dependencia>
        <dependencia>pesssoaclassificacao</dependencia>
        <dependencia>workflowcommonfeature</dependencia>
        <dependencia>unidades</dependencia>
        <dependencia>grade</dependencia>
        <dependencia>docfis</dependencia>
        <dependencia>producao</dependencia>
        <dependencia>usuario</dependencia>
        <dependencia>resources</dependencia>
        <dependencia>controlesaldosprodutos</dependencia>
        <dependencia>formapagamento</dependencia>
        <dependencia>entidadesempresariais</dependencia>
        <dependencia>ciclofaturamento</dependencia>
        <dependencia>bi</dependencia>
        <dependencia>projetos</dependencia>
        <dependencia>nscertificadodigital</dependencia>
        <dependencia>numeroserie</dependencia>
        <dependencia>contafinanceira</dependencia>
        <dependencia>nsintegradorged</dependencia>
        <dependencia>etiqueta</dependencia>
        <dependencia>nsxeutil</dependencia>
        <dependencia>ncm</dependencia>
        <dependencia>requisicaoalmoxarifado</dependencia>
        <dependencia>rateios</dependencia>
        <dependencia>etiqueta_base</dependencia>
        <dependencia>categoriadeproduto</dependencia>
        <dependencia>configuracao</dependencia>
        <dependencia>movimento</dependencia>
        <dependencia>cfopexclusao_fatura</dependencia>
        <dependencia>participantes</dependencia>
        <dependencia>veiculo</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>objetosservicos</dependencia>
        <dependencia>itemestabelecimento</dependencia>
        <dependencia>financeiro</dependencia>
        <dependencia>cest</dependencia>
        <dependencia>nsproxy</dependencia>
        <dependencia>moeda</dependencia>
        <dependencia>produto</dependencia>
        <dependencia>pretitulos</dependencia>
        <dependencia>docengine</dependencia>
        <dependencia>scrittamateriais</dependencia>
        <dependencia>nslog</dependencia>
        <dependencia>nsemail</dependencia>
        <dependencia>operacoes</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls_bkp/NSJCONVERSOR.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>NSJCONVERSOR</nome>
    <path>source\desktop_new\projects\conversor\nsjConversor.dproj</path>
    <dependencias>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>NSPROTECAO</dependencia>
        <dependencia>NSJPERSONA</dependencia>
        <dependencia>NSXEUTIL</dependencia>
        <dependencia>NSJCONTABIL</dependencia>
        <dependencia>NSLOG</dependencia>
        <dependencia>NSJAPI</dependencia>
    </dependencias>
</projeto>
