=== Nasajon/nsbuild/nsjBuild/xml/nsjBuildProject.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.nasajon.com.br/nsjbuild"
			elementFormDefault="qualified"
			attributeFormDefault="unqualified"
			xmlns:nsjb="http://www.nasajon.com.br/nsjbuild">

	<xs:element name="projeto">
        <xs:complexType>
			<xs:sequence>
				
				<xs:element name="nome" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Nome do projeto (identificador que precisa ser único; sugere-se utilizar o nome do arquivo ".dproj").
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Nome do programdor responsável pela criação do pacote (sugere-se utilizar a identidade Nasajon).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dataCriacao" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Data e hora da criação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resumo" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Comentário para documentação do projeto.
						</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="path" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Caminho relativo do projeto, a partir do diretório do repositório "erp" (caminho do arquivo "dproj" do projeto atual).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="dependencias" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Lista de projetos dos quais o projeto atual depende.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dependencia" type="xs:string" minOccurs="1" maxOccurs="1000">
								<xs:annotation>
									<xs:documentation>
										Nome do projeto do qual o projeto atual depende.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ignore" type="xs:boolean" minOccurs="0" maxOccurs="1" nillable="false">
					<xs:annotation>
						<xs:documentation>
							Se for true, o projeto será ignorado pelo nsbuild (não entrará no grafo de compilação).
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
    </xs:element>
</xs:schema>

=== Nasajon/nsbuild/buildXMLs/xmls/dashboardclientes.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>dashboardclientes</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\commonfeature\dashboardclientes\package\dashboardclientes.dproj</path>
    <dependencias>
        <dependencia>followup</dependencia>
        <dependencia>nstraducao</dependencia>
        <dependencia>commonutils_static</dependencia>
        <dependencia>nsdashboard</dependencia>
        <dependencia>objetosservicos</dependencia>
        <dependencia>financeiro</dependencia>
        <dependencia>proposta</dependencia>
        <dependencia>ordensdeservicobase</dependencia>
        <dependencia>objetosservicosbase</dependencia>
        <dependencia>propostabase</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/MOVIMENTO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>MOVIMENTO</nome>
    <path>source\desktop_new\commonfeature\movimento\package\movimento.dproj</path>
    <dependencias>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>ITEM</dependencia>
        <dependencia>PRODUTO</dependencia>
        <dependencia>NSORM</dependencia>
        <dependencia>DOCFIS</dependencia>
        <dependencia>SCRITTAMATERIAIS</dependencia>
        <dependencia>CONFIGURACAO</dependencia>
        <dependencia>OPERACOES</dependencia>
        <dependencia>ENTIDADESEMPRESARIAIS</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/PRODUCAO.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>PRODUCAO</nome>
    <path>source\desktop_new\commonfeature\producao\package\producao.dproj</path>
    <dependencias>
        <dependencia>ETIQUETA</dependencia>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>PRODUTO</dependencia>
        <dependencia>NSJREPORTEDITOR</dependencia>
        <dependencia>NSORM</dependencia>
        <dependencia>SCRITTAMATERIAIS</dependencia>
        <dependencia>RESOURCES</dependencia>
        <dependencia>ETIQUETA_BASE</dependencia>
        <dependencia>RELATORIOS</dependencia>
        <dependencia>CONFIGURACAO</dependencia>
        <dependencia>OPERACOES</dependencia>
        <dependencia>ENTIDADESEMPRESARIAIS</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/CONTROLESALDOSPRODUTOS.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>controlesaldosprodutos</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\commonfeature\controlesaldosprodutos\package\controlesaldosprodutos.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>documentositens</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>nsjusuarios</dependencia>
        <dependencia>resources</dependencia>
        <dependencia>categoriadeproduto</dependencia>
        <dependencia>configuracao</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/buildXMLs/xmls/propostabase.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>propostabase</nome>
    <autor>[Identidde Nasajon]</autor>
    <dataCriacao>[01/01/1900]</dataCriacao>
    <resumo>[Indicar resumo para documentação do projeto]</resumo>
    <path>source\desktop_new\commonfeature\propostabase\package\propostabase.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>itensfaturamentobase</dependencia>
        <dependencia>financeiro</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>nsintegradorged</dependencia>
        <dependencia>naturezascontratos</dependencia>
        <dependencia>followup</dependencia>
        <dependencia>nstraducao</dependencia>
        <dependencia>componentesbase</dependencia>
        <dependencia>rps</dependencia>
        <dependencia>documentositens</dependencia>
        <dependencia>nsjusuarios</dependencia>
        <dependencia>propostaoperacao</dependencia>
        <dependencia>ofertasbase</dependencia>
        <dependencia>formapagamento</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/OFERTASBASE.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>ofertasbase</nome>
    <path>source\desktop_new\commonfeature\ofertasbase\package\ofertasbase.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>componentesbase</dependencia>
        <dependencia>itensfaturamentobase</dependencia>
        <dependencia>servicostecnicos</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>catalogodeofertas</dependencia>
        <dependencia>documentositensescopo</dependencia>
        <dependencia>objetosservicosbase</dependencia>
        <dependencia>gruposdecomponentes</dependencia>
        <dependencia>atributos</dependencia>
    </dependencias>
    <ultimaCompilacao>2016-08-20T09:42:34.591-03:00</ultimaCompilacao>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls_bkp/DASHBOARDCLIENTES.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>DASHBOARDCLIENTES</nome>
    <path>source\desktop_new\commonfeature\dashboardclientes\package\dashboardclientes.dproj</path>
    <dependencias>
        <dependencia>FOLLOWUP</dependencia>
        <dependencia>NSTRADUCAO</dependencia>
        <dependencia>COMMONUTILS_STATIC</dependencia>
        <dependencia>NSDASHBOARD</dependencia>
        <dependencia>OBJETOSSERVICOS</dependencia>
        <dependencia>FINANCEIRO</dependencia>
        <dependencia>PROPOSTA</dependencia>
        <dependencia>ORDENSDESERVICOBASE</dependencia>
        <dependencia>OBJETOSSERVICOSBASE</dependencia>
        <dependencia>PROPOSTABASE</dependencia>
        <dependencia>ENTIDADESEMPRESARIAIS</dependencia>
    </dependencias>
</projeto>

=== Nasajon/nsbuild/nsjBuild/xmls/SERVICOSTECNICOS.nsproj.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projeto xmlns="http://www.nasajon.com.br/nsjbuild" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nasajon.com.br/nsjbuild nsjBuildProject.xsd ">
    <nome>servicostecnicos</nome>
    <path>source\desktop_new\commonfeature\servicostecnicos\package\servicosTecnicos.dproj</path>
    <dependencias>
        <dependencia>commonutils_static</dependencia>
        <dependencia>itensfaturamento</dependencia>
        <dependencia>itensfaturamentobase</dependencia>
        <dependencia>nsorm</dependencia>
        <dependencia>classificacaofinanceira</dependencia>
        <dependencia>tiposdeservicos</dependencia>
        <dependencia>entidadesempresariais</dependencia>
    </dependencias>
    <ultimaCompilacao>2016-08-20T09:42:21.654-03:00</ultimaCompilacao>
</projeto>
